version: "3.8"

services:
  db:
    image: postgres:15
    container_name: ems_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ems_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ems_backend_server
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_NAME=ems_db
      - JWT_SECRET=mysecretkey
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: ../backend/Dockerfile # Reuse node build style or standard frontend docker build
    container_name: ems_frontend_client
    restart: always
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  postgres_data:
